### ISSUE TITLE
Idea: stop wrapping Mantine, provide behavior hooks instead

### ISSUE THREAD

**Issue by gustavopch** [airplanedev/views#47]
I've sent this idea to support by email, but I think I should also send here because it's a very technical suggestion (even though it would impact the business as a whole).

---

Currently, Airplane components are basically wrapped Mantine components. That means a lot of work if Airplane wants to provide all of their components and that's probably why you only provide a few (and you're still using v5 even though v6 has been out for 2 months).

I believe there's a more efficient way to do it. Let users import components directly from Mantine and have access to 100% of what Mantine offers without wasting your engineering time and, instead, simply provide hooks to attach Airplane behavior to Mantine components.

```ts
import { Button } from '@mantine/core'
import { useTaskQuery } from 'airplane'

const task = useTaskMutation({ slug: 'do_something' })

<Button {...task.attachToButton()} />
```

That's exactly why React Hooks exist: to separate behavior from visuals. Leverage it! **And then use the saved engineering time for more innovative and exciting features.**

Particularly, I've decided to use Mantine components directly to have access to their whole library.

**Comment by leeweisberger** [comment]
Thanks for the feedback @gustavopch.

When we built Airplane Views, one of our main goals was to build a pretty open system that serves a wide range of developers. Since a view is just a react application, you can choose to use all, some or none of our prebuilt components. In fact, you can deploy a view onto Airplane without even using this library!

We decided to export a curated set of components for a few reasons:
1. Some Airplane developers are not React experts or even frontend experts. While an experienced frontend dev might be comfortable choosing and reaching into a generic, open source component library, a data scientist may not.
2. Many of our components are not straight-passthroughs to Mantine. We are opinionated about which options we expose and their defaults as well as frequently adding layers on top of the underlying components to optimize for developing good looking components aimed at internal tools.
3. We have added a few of our own components, the Table and Stack being examples, on top of Mantine's library.
4. We are able to customize the look and feel of our components to match the Airplane UI so your view integrates seamlessly into Airplane. While we could provide helper functions for customizing the Mantine theme, it's simpler to have everything looking clean out of the box. In the future, we may add our own theming library that is deeply integrated with the rest of the Airplane UI.
5. Our components are automatically integrated with the views component state and Airplane tasks. While you can use the hooks that we expose, it's simpler, especially for developers unfamiliar with React hooks, to get this functionality for free.
6. The use of Mantine under the hood is an implementation detail. We are able to switch out components to using a different library or using our own custom components instead without troubling the user.

Although we think this makes for an easy to use product that produces great internal tools out of the box, you are absolutely free to use Mantine or any other component library that you are comfortable with, either instead of or in addition to our components. Please let us know if you run into any issues integrating your components into your view. We tried to encapsulate functionality into hooks (calling tasks, routing, etc...) so you are able to make use of them whether or not you choose to use our components.

**Comment by gustavopch** [comment]
Thanks for the detailed response.

I understand your rationale for this architecture. I think the main point of my suggestion is that maybe focusing on hooks instead of components would be more flexible, composable and lean. It would perhaps leverage React better. I mean, could be worth considering if something like `<Button {...doSomethingTask.attach()}>` would actually be scary for non-React developers. Of course, such a change would require a user research.

I wrote this idea because I thought such an architecture could give your team more time to focus on more interesting features (it would benefit me as a customer) instead of spending time trying to catch up with Mantine (they have 120+ components, Airplane has ~30; they are at v6, Airplane is using v5).

In fact, in my views, I'm using Mantine and React Query directly to have access to all components and be able to use `useInfiniteQuery`. At the moment, the only thing I'm importing from `@airplane/views` is `executeTask`.

Anyway, take this as a well-intentioned idea from someone wishing Airplane to thrive. Feel free to close the issue as it's probably not actionable.
